# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-07 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciphertext', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciphertext',
            name='owner',
        ),
    ]
